# Hyperparameters for MAP-Elites Snake Training
# Load with: cargo run -- --config config.toml

population_size =  8192 #4096           # Snakes per generation (non più limitato ai core)
mutation_rate = 0.05
mutation_strength = 0.3
crossover_rate = 0.3
max_frames = 2000
base_steps_without_food = 60
steps_per_segment = 8
grid_resolution = 20
auto_save_interval = 50
